platform :ios, '8.0'

target 'ApolloExample' do
  use_frameworks!

  # Pods for ApolloExample
  pod 'Apollo', path: '../'

  target 'ApolloTests' do
    inherit! :search_paths
  end

  target 'ApolloPerformanceTests' do
    inherit! :search_paths
  end

  target 'StarWarsAPI' do
    inherit! :search_paths
  end

end
