/// An enum generated by omitting deprecated cases
public enum EnumOmittingDeprecatedCases: RawRepresentable, Codable, Equatable, Hashable, CaseIterable {
  public typealias RawValue = String

  /// This value is not deprecated
  case notDeprecated
  /// An EnumOmittingDeprecatedCases type not defined at the time this enum was generated
  case __unknown(String)

  public var rawValue: String {
    switch self {
    case .notDeprecated: return "notDeprecated"
    case .__unknown(let value): return value
    }
  }

  public init(rawValue: String) {
    switch rawValue {
    case "notDeprecated": self = .notDeprecated
    default: self = .__unknown(rawValue)
    }
  }

  public static var allCases: [EnumOmittingDeprecatedCases] {
    [
      .notDeprecated,
    ]
  }
}
