filegroup(
    name = "ApolloCoreFiles",
    srcs = glob(["ApolloCore/*.swift"]),
    visibility = ["//:__pkg__"],
)

filegroup(
    name = "ApolloFiles",
    srcs = glob(["Apollo/*.swift"]),
    visibility = ["//:__pkg__"],
)

filegroup(
    name = "ApolloCodegenLibFiles",
    srcs = glob(["ApolloCodegenLib/*.swift"]),
    visibility = ["//:__pkg__"],
)

filegroup(
    name = "ApolloSQLiteFiles",
    srcs = glob(["ApolloSQLite/*.swift"]),
    visibility = ["//:__pkg__"],
)

filegroup(
    name = "ApolloWebSocketFiles",
    srcs = glob(["ApolloWebSocket/*.swift"]),
    visibility = ["//:__pkg__"],
)
