name: Question
description: Ask a general question about the project
labels: [ "question" ]
body:
  - type: markdown
    attributes:
      value: |
        Please search the existing resources before asking your question:
        - [`CHANGELOG.md`](https://github.com/apollographql/apollo-ios/blob/main/CHANGELOG.md)
        - [Documentation](https://www.apollographql.com/docs/ios)
        - [GitHub issues](https://github.com/apollographql/apollo-ios/issues)
        - [StackOverflow](https://stackoverflow.com/questions/tagged/apollo-ios)
        - [GraphOS Discord](https://discord.com/invite/graphos)
        - [Community forums](https://community.apollographql.com/tag/mobile)

        Please avoid duplicating issues and discussions. If you'd like a GitHub issue to be reopened, leave a message on the issue.
  - type: textarea
    attributes:
      label: Question
      placeholder: Please reconsider using this template and use one of the listed resources instead.
    validations:
      required: true
