name: Question
description: Ask a general question about the project
labels: [ "question" ]
body:
  - type: markdown
    attributes:
      value: |
        Please search the existing resources before asking your question:
        - [`CHANGELOG`](https://github.com/apollographql/apollo-ios/blob/main/CHANGELOG.md)
        - [Documentation](https://www.apollographql.com/docs/ios)
        - [GitHub issues](https://github.com/apollographql/apollo-ios/issues)
        - [Community](https://community.apollographql.com/tag/mobile)
        - [StackOverflow](https://stackoverflow.com/questions/tagged/apollo-ios)

        Questions are welcome but avoid duplicating issues and discussions. If you'd like a GitHub issue to be reopened, please leave a message on the issue.
  - type: textarea
    attributes:
      label: Question
      description: Enter your question here.
    validations:
      required: true
