# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'pod-install-test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for codegen-cli-issue
  if ENV['CIRCLE_PR_REPONAME'] != nil
    pod 'Apollo', :git => "https://github.com/#{ENV['CIRCLE_PR_USERNAME']}/#{ENV['CIRCLE_PR_REPONAME']}.git", :commit => ENV['CIRCLE_SHA1']
  else
    pod 'Apollo', :git => 'https://github.com/apollographql/apollo-ios.git', :branch => ENV['CIRCLE_BRANCH']
  end
end
