# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'MyCustomProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Apollo', :path => '../../../..'

  target 'MyCustomProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyCustomProjectUITests' do
    # Pods for testing
  end

end
