# Uncomment the next line to define a global platform for your project
platform :osx, '12.3'

target 'CocoaPodsProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoaPodsProject
  pod 'Apollo', :path => '../../../'
  pod 'Apollo/ApolloTestSupport', :path => '../../../'

  target 'CocoaPodsProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
