# Uncomment the next line to define a global platform for your project
platform :osx, '13.1'

target 'MyCustomProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Apollo', :path => '../../../'
  pod 'Apollo/ApolloTestSupport', :path => '../../../'

  target 'MyCustomProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyCustomProjectUITests' do
    # Pods for testing
  end

end
